name: app-merge

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

permissions:
  contents: read
  packages: write
  id-token: write
  issues: write

env:
  IMAGE: ghcr.io/${{ github.repository }}
  VM: -g rg-devsecops-lab -n vm-devsecops-lab --command-id RunShellScript --scripts @app/scripts/deploy.sh

jobs:
  #[DOC] - https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images
  app-docker-push:
    name: "app-docker-push"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ghcr-login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker-build-push
        uses: docker/build-push-action@v7
        with:
          context: app
          push: true
          tags: ${{ env.IMAGE }}:${{ github.run_number }}

  #[DOC] - https://learn.microsoft.com/en-us/cli/azure/vm/run-command#az-vm-run-command-invoke
  #[DOC] - https://github.com/zaproxy/action-full-scan
  app-deploy:
    name: "app-deploy"
    runs-on: ubuntu-latest
    needs:
      - app-docker-push

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: azure-login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_APPLY }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: vm-deploy
        run:  az vm run-command invoke $VM --parameters $IMAGE:${{ github.run_number }}

      - name: dast-zap
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: ${{ vars.APP_URL }}
          rules_file_name: .zap/rules.tsv
          cmd_options: -I
          fail_action: true

      - name: vm-rollback
        if: failure() && github.run_number > 1
        run:  az vm run-command invoke $VM --parameters $IMAGE:$(( ${{ github.run_number }} - 1 ))
