name: lab

on: pull_request

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run --rm checkov
        working-directory: lab

  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod -R 777 reports
        working-directory: lab
      - run: docker compose up -d app
        working-directory: lab
      - run: docker compose run --rm zap
        working-directory: lab
